### ISSUE TITLE
Crash when running on lower versions of Android

### ISSUE THREAD

**Issue by mrapitis** [CustomSDL/sdl_android_launcher#11]
Seems some classes are missing when using the current compile version. Please see details below.
https://stackoverflow.com/questions/45232457/android-studio-notification-channel-cannot-be-imported

```
2021-09-24 11:41:47.410 10073-10073/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.luxoft.sdl_core, PID: 10073
    java.lang.NoClassDefFoundError: Failed resolution of: Landroid/app/NotificationChannel;
        at org.luxoft.sdl_core.SdlLauncherService.enterForeground(SdlLauncherService.java:167)
        at org.luxoft.sdl_core.SdlLauncherService.onStartCommand(SdlLauncherService.java:55)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3522)
        at android.app.ActivityThread.-wrap23(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1685)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:156)
        at android.app.ActivityThread.main(ActivityThread.java:6623)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "android.app.NotificationChannel" on path: DexPathList[[zip file "/data/app/org.luxoft.sdl_core-1/base.apk"],nativeLibraryDirectories=[/data/app/org.luxoft.sdl_core-1/lib/arm64, /data/app/org.luxoft.sdl_core-1/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64, /system/vendor/lib64, /product/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at org.luxoft.sdl_core.SdlLauncherService.enterForeground(SdlLauncherService.java:167) 
        at org.luxoft.sdl_core.SdlLauncherService.onStartCommand(SdlLauncherService.java:55) 
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3522) 
        at android.app.ActivityThread.-wrap23(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1685) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:156) 
        at android.app.ActivityThread.main(ActivityThread.java:6623) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832) 
```

**Comment by YaroslavLutsenko** [comment]
Closed #12
